services:
  - type: web
    name: recipe-ai-backend
    env: node
    rootDir: Page_Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
