import {
  Zap,
  Sparkles,
  Droplet,
  HeartPulse,
  ShieldCheck,
  CircleDot,
  Leaf,
  TrendingUp,
  Sprout,
  Activity,
  UserRound,
  Smile,
  Nut,
  Milk,
  Egg,
  Fish,
  Shrimp,
  Wheat,
  Bean,
  FlaskRound,
  Umbrella,
  Lightbulb,
  CircleEllipsis,
  Popcorn,
  FlaskConical,
  Beaker,
  Cherry,
  Salad,
  ChefHat,
  Snowflake,
  ThermometerSun,
  Flame,
  Citrus,
  Candy,
  Grid2x2,
} from "lucide-react";

// Neutral icon treatment shared by every allergy card — the reference design
// keeps these monochrome (unlike the colorful per-goal icons on step 2) and
// only breaks the pattern for "None of these".
const NEUTRAL = "bg-cream-200 text-ink-soft";

// Config-driven steps power a single generic renderer in CreateRecipe.jsx.
// "dish" is the only step with custom UI (free-text input); the rest are
// icon-card selection grids that share the same layout.
export const WIZARD_STEPS = [
  { key: "dish", number: 1, label: "Dish", type: "dish" },
  {
    key: "goals",
    number: 2,
    label: "Health Goal",
    type: "options",
    selectionMode: "multi",
    max: 3,
    eyebrow: "Step 2 of 5",
    title: "What's your health goal today?",
    subtitle: "Choose one or more. This helps us personalize your recipe better.",
    nextLabel: "Allergies",
    moreLabel: "More goals",
    footerLeft: "more",
    illustrationIcon: Salad,
    options: [
      { value: "High Protein", label: "High Protein", sub: "Build & repair muscles", icon: Zap, color: "bg-orange-100 text-orange-500" },
      { value: "Weight Loss", label: "Weight Loss", sub: "Burn fat & feel lighter", icon: Sparkles, color: "bg-lime-100 text-lime-600" },
      { value: "Diabetes Friendly", label: "Diabetes Friendly", sub: "Stabilize sugar levels", icon: Droplet, color: "bg-sky-100 text-sky-500" },
      { value: "Heart Healthy", label: "Heart Healthy", sub: "Good for your heart", icon: HeartPulse, color: "bg-rose-100 text-rose-500" },
      { value: "Low Cholesterol", label: "Low Cholesterol", sub: "Manage cholesterol naturally", icon: ShieldCheck, color: "bg-purple-100 text-purple-500" },
      { value: "Low Sodium", label: "Low Sodium", sub: "Reduce salt intake", icon: CircleDot, color: "bg-teal-100 text-teal-500" },
      { value: "High Fiber", label: "High Fibre", sub: "Better digestion & gut health", icon: Leaf, color: "bg-emerald-100 text-emerald-600" },
      { value: "Muscle Gain", label: "Muscle Gain", sub: "Gain lean muscle", icon: TrendingUp, color: "bg-amber-100 text-amber-600" },
      { value: "Plant Based", label: "Plant Based", sub: "100% plant focused", icon: Sprout, color: "bg-teal-100 text-teal-600" },
      { value: "Gut Friendly", label: "Gut Friendly", sub: "Good bacteria, better you", icon: Activity, color: "bg-pink-100 text-pink-500" },
      { value: "Women's Health", label: "Women's Health", sub: "Hormone & period support", icon: UserRound, color: "bg-fuchsia-100 text-fuchsia-500" },
      { value: "Kids Friendly", label: "Kids Friendly", sub: "Nutritious & kid-approved", icon: Smile, color: "bg-yellow-100 text-yellow-600" },
    ],
    moreOptions: [
      { value: "Anti-Inflammatory", label: "Anti-Inflammatory", sub: "Soothe & reduce swelling", icon: Flame, color: "bg-red-100 text-red-500" },
      { value: "Low Carb", label: "Low Carb", sub: "Fewer carbs, steadier energy", icon: Salad, color: "bg-lime-100 text-lime-600" },
      { value: "Family Friendly", label: "Family Friendly", sub: "Loved by the whole table", icon: Smile, color: "bg-orange-100 text-orange-500" },
      { value: "Better Digestion", label: "Better Digestion", sub: "Easy on your stomach", icon: Activity, color: "bg-emerald-100 text-emerald-600" },
    ],
  },
  {
    key: "allergies",
    number: 3,
    label: "Allergies",
    type: "options",
    selectionMode: "multi",
    eyebrow: "Step 3 of 5",
    title: "Any allergies or ingredients you want us to avoid?",
    subtitle: "Select all that apply. This helps us keep your recipes safe & suitable.",
    nextLabel: "Cooking Style",
    footerLeft: "info",
    infoLabel: "Why we ask this?",
    infoText:
      "We use this only to steer recipe generation away from unsafe ingredients — it's never shared or sold, and you can change it any time.",
    illustrationIcon: ShieldCheck,
    allowCustomInput: true,
    customInputLabel: "Anything else we should avoid?",
    customInputHint: "Type any ingredient or allergen not listed above",
    customInputPlaceholder: "e.g. Coconut, Cumin, Yeast...",
    options: [
      { value: "Peanut", label: "Peanuts", sub: "Peanuts & peanut oil", icon: Nut, color: NEUTRAL },
      { value: "Tree Nut", label: "Tree Nuts", sub: "Almonds, cashews, walnuts", icon: Nut, color: NEUTRAL },
      { value: "Dairy", label: "Dairy", sub: "Milk, cheese, yogurt", icon: Milk, color: NEUTRAL },
      { value: "Egg", label: "Eggs", sub: "All egg-based ingredients", icon: Egg, color: NEUTRAL },
      { value: "Gluten", label: "Gluten", sub: "Wheat, barley, rye", icon: Wheat, color: NEUTRAL },
      { value: "Soy", label: "Soy", sub: "Soybean derived products", icon: Bean, color: NEUTRAL },
      { value: "Shellfish", label: "Shellfish", sub: "Shrimp, crab, lobster", icon: Shrimp, color: NEUTRAL },
      { value: "Fish", label: "Fish", sub: "Finned fish varieties", icon: Fish, color: NEUTRAL },
      { value: "Sesame", label: "Sesame", sub: "Seeds & sesame oil", icon: CircleDot, color: NEUTRAL },
      { value: "Mustard", label: "Mustard", sub: "Mustard seeds & sauces", icon: FlaskRound, color: NEUTRAL },
      { value: "Mushroom", label: "Mushrooms", sub: "All fungi varieties", icon: Umbrella, color: NEUTRAL },
      { value: "Onion", label: "Onion", sub: "Onion & onion powder", icon: Lightbulb, color: NEUTRAL },
      { value: "Garlic", label: "Garlic", sub: "Garlic & garlic powder", icon: CircleEllipsis, color: NEUTRAL },
      { value: "Corn", label: "Corn", sub: "Corn & corn starch", icon: Popcorn, color: NEUTRAL },
      { value: "Sulfites", label: "Sulfites", sub: "Preservatives in dried fruit, wine", icon: FlaskConical, color: NEUTRAL },
      { value: "Artificial Sweeteners", label: "Artificial Sweeteners", sub: "Aspartame, sucralose & more", icon: Beaker, color: NEUTRAL },
      { value: "Nightshades", label: "Nightshades", sub: "Tomato, potato, eggplant, pepper", icon: Cherry, color: NEUTRAL },
      { value: "None", label: "None of these", sub: "No known allergies", icon: Leaf, color: "bg-olive-soft text-olive-dark", accent: "olive" },
    ],
  },
  {
    key: "cookingStyle",
    number: 4,
    label: "Cooking Style",
    type: "options",
    selectionMode: "single",
    eyebrow: "Step 4 of 5",
    title: "What's your cooking style?",
    subtitle: "Pick the one that fits how you like to eat.",
    nextLabel: "Taste & Spice",
    illustrationIcon: ChefHat,
    options: [
      { value: "Vegetarian", label: "Vegetarian", sub: "No meat or fish", icon: Salad, color: "bg-emerald-100 text-emerald-600" },
      { value: "Vegan", label: "Vegan", sub: "100% plant based", icon: Sprout, color: "bg-lime-100 text-lime-600" },
      { value: "Pescatarian", label: "Pescatarian", sub: "Vegetarian plus fish", icon: Fish, color: "bg-teal-100 text-teal-500" },
      { value: "Halal", label: "Halal", sub: "Prepared per Halal guidelines", icon: ShieldCheck, color: "bg-amber-100 text-amber-600" },
      { value: "Kosher", label: "Kosher", sub: "Prepared per Kosher guidelines", icon: ShieldCheck, color: "bg-sky-100 text-sky-500" },
      { value: "Jain", label: "Jain", sub: "No root vegetables", icon: Leaf, color: "bg-emerald-100 text-emerald-600" },
      { value: "Gluten Free", label: "Gluten Free", sub: "No wheat or gluten", icon: Wheat, color: "bg-orange-100 text-orange-500" },
      { value: "Dairy Free", label: "Dairy Free", sub: "No milk or dairy", icon: Milk, color: "bg-sky-100 text-sky-500" },
      { value: "Egg Free", label: "Egg Free", sub: "No eggs", icon: Egg, color: "bg-amber-100 text-amber-600" },
      { value: "No Preference", label: "No Preference", sub: "I'll eat anything healthy", icon: ChefHat, color: "bg-gray-100 text-gray-500" },
    ],
  },
  {
    key: "spiceLevel",
    number: 5,
    label: "Taste & Spice",
    type: "options",
    selectionMode: "single",
    eyebrow: "Step 5 of 5",
    title: "How spicy do you like it?",
    subtitle: "Choose your preferred taste & spice level.",
    nextLabel: "Generate Recipe",
    illustrationIcon: Flame,
    options: [
      { value: "Mild", label: "Mild", sub: "Little to no heat", icon: Snowflake, color: "bg-sky-100 text-sky-500" },
      { value: "Medium", label: "Medium", sub: "Balanced warmth", icon: ThermometerSun, color: "bg-amber-100 text-amber-600" },
      { value: "Spicy", label: "Spicy", sub: "Bold heat kick", icon: Flame, color: "bg-orange-100 text-orange-500" },
      { value: "Extra Spicy", label: "Extra Spicy", sub: "Fire it up", icon: Flame, color: "bg-rose-100 text-rose-500" },
      { value: "Tangy & Sour", label: "Tangy & Sour", sub: "Zesty citrus notes", icon: Citrus, color: "bg-lime-100 text-lime-600" },
      { value: "Sweet & Savory", label: "Sweet & Savory", sub: "Balanced sweetness", icon: Candy, color: "bg-fuchsia-100 text-fuchsia-500" },
    ],
  },
];

export const MoreOptionsIcon = Grid2x2;
